//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bilgisayarlar
    {
        public int id { get; set; }
        public string programlar { get; set; }
        public System.DateTime eklenmeTarihi { get; set; }
        public string isletimSistemi { get; set; }
        public int kayitID { get; set; }
    }
}
