//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class durumGecmisi
    {
        public int id { get; set; }
        public int islemciKullanimi { get; set; }
        public int totalRam { get; set; }
        public int anlikKullanilanRam { get; set; }
        public int kullanilanTotalDiskSize { get; set; }
        public int anlikKullanilanDiskSize { get; set; }
        public int bilgisayarID { get; set; }
        public System.DateTime guncellenmeTarihi { get; set; }
    }
}
